clc;clear;close all;
x = input('Enter sequence x : ');
h = input('Enter sequence h: ');
N = length(x) + length(h) - 1;
x_pad = [x zeros(1, N - length(x))];
h_pad = [h zeros(1, N - length(h))];
X = fft(x_pad, N);
H = fft(h_pad, N);
Y = X .* H;
y_linear = ifft(Y, N);
disp('Linear convolution result using DFT/IDFT:');
disp(y_linear);
figure;
subplot(3,1,1);
stem(0:length(x_pad)-1, x_pad, 'filled');
title('Sequence x[n] (zero-padded)');
xlabel('n');
ylabel('x[n]');
grid on;
subplot(3,1,2);
stem(0:length(h_pad)-1, h_pad, 'filled');
title('Sequence h[n] (zero-padded)');
xlabel('n');
ylabel('h[n]');
grid on;
subplot(3,1,3);
stem(0:N-1, real(y_linear), 'filled');
title('Linear Convolution y[n] = x[n] * h[n]');
xlabel('n');
ylabel('y[n]');
grid on;
