clc;
clear;
close all;
N = input("Enter order (odd number): ");
n = -(N-1)/2 : (N-1)/2;
wR = ones(1,N);
subplot(3,2,1);
stem(n,wR);
title("Rectangular Window");
wT = 1 - (abs(n)/((N-1)/2));
subplot(3,2,2);
stem(n,wT);
title("Triangular Window");
wh = 0.5 + 0.5*cos((2*pi*n)/(N-1));
subplot(3,2,3);
stem(n,wh);
title("Hanning Window");
wH = 0.54 + 0.46*cos((2*pi*n)/(N-1));
subplot(3,2,4);
stem(n,wH);
title("Hamming Window");
wB = 0.42 + 0.5*cos((2*pi*n)/(N-1)) + 0.08*cos((4*pi*n)/(N-1));
subplot(3,2,5);
stem(n,wB);
title("Blackman Window"); 
beta = 5;
wK = kaiser(N,beta); 
subplot(3,2,6);
stem(n,wK);
title("Kaiser Window");